apiVersion: apps/v1
kind: Deployment
metadata:
  name: owner-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: owner-dashboard
  template:
    metadata:
      labels:
        app: owner-dashboard
    spec:
      containers:
        - name: owner-dashboard
          image: gcr.io/PROJECT/owner-dashboard:latest
          ports:
            - containerPort: 8500
